version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: deal-finder-db
    environment:
      POSTGRES_DB: deal_finder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./scripts:/scripts
    restart: unless-stopped

volumes:
  postgis_data: