def get_mock_deals():
    """Return mock deal data for testing with real Zillow-style URLs and addresses."""
    return [
        # Residential Properties with Real Addresses
        {
            'id': 1,
            'title': '4070 Runnymede Dr, Lilburn, GA 30047',
            'price': 425000,
            'url': 'https://www.zillow.com/homedetails/4070-Runnymede-Dr-Lilburn-GA-30047/14744841_zpid/',
            'source': 'zillow',
            'created_at': '2025-01-15T10:00:00Z',
            'lat': 33.8616,
            'lng': -84.1197,
            'city': 'Lilburn',
            'state': 'GA',
            'county': 'Gwinnett',
            'zip_code': '30047',
            'property_category': 'residential',
            'property_type': 'house',
            'bedrooms': 4,
            'bathrooms': 3,
            'square_feet': 2400,
            'lot_size': 0.5,  # acres
            'year_built': 1998,
            'parking_spaces': 2,
            'has_garage': True,
            'has_pool': False,
            'has_gym': False,
            'pet_friendly': True,
            'crime_rate': 'low',
            'flood_zone': 'X',
            'school_rating': 8.2,
            'sewage_system': 'municipal',
            'images': [
                'https://photos.zillowstatic.com/fp/1234567890-4070-Runnymede-Dr-Lilburn-GA-30047.jpg',
                'https://photos.zillowstatic.com/fp/1234567891-4070-Runnymede-Dr-Lilburn-GA-30047.jpg',
                'https://photos.zillowstatic.com/fp/1234567892-4070-Runnymede-Dr-Lilburn-GA-30047.jpg',
                'https://photos.zillowstatic.com/fp/1234567893-4070-Runnymede-Dr-Lilburn-GA-30047.jpg'
            ],
            'zillow_id': '14744841',
            'match_score': 0.89,
            'distance_meters': 1200,
            'price_diff_percent': -3.5,
            'agent_name': 'Jennifer Martinez',
            'agent_phone': '(770) 555-0123',
            'agent_email': 'jennifer.martinez@kw.com',
            'brokerage': 'Keller Williams Realty',
            'on_market': True
        },
        {
            'id': 2,
            'title': '1234 Peachtree St NW, Atlanta, GA 30309',
            'price': 750000,
            'url': 'https://www.zillow.com/homedetails/1234-Peachtree-St-NW-Atlanta-GA-30309/35849789_zpid/',
            'source': 'zillow',
            'created_at': '2025-01-14T15:30:00Z',
            'lat': 33.7857,
            'lng': -84.3846,
            'city': 'Atlanta',
            'state': 'GA',
            'county': 'Fulton',
            'zip_code': '30309',
            'property_category': 'residential',
            'property_type': 'condo',
            'bedrooms': 2,
            'bathrooms': 2,
            'square_feet': 1400,
            'lot_size': None,
            'year_built': 2005,
            'parking_spaces': 1,
            'has_garage': False,
            'has_pool': True,
            'has_gym': True,
            'pet_friendly': True,
            'crime_rate': 'medium',
            'flood_zone': 'X',
            'school_rating': 7.8,
            'sewage_system': 'municipal',
            'images': [
                'https://photos.zillowstatic.com/fp/9876543210-1234-Peachtree-St-NW-Atlanta-GA-30309.jpg',
                'https://photos.zillowstatic.com/fp/9876543211-1234-Peachtree-St-NW-Atlanta-GA-30309.jpg',
                'https://photos.zillowstatic.com/fp/9876543212-1234-Peachtree-St-NW-Atlanta-GA-30309.jpg'
            ],
            'zillow_id': '35849789',
            'match_score': 0.94,
            'distance_meters': 800,
            'price_diff_percent': 5.2,
            'agent_name': 'Marcus Johnson',
            'agent_phone': '(404) 555-0456',
            'agent_email': 'marcus@atlrealty.com',
            'brokerage': 'Atlanta Realty Partners',
            'on_market': True
        },
        {
            'id': 3,
            'title': '5678 Piedmont Rd, Atlanta, GA 30324',
            'price': 350000,
            'url': 'https://www.zillow.com/homedetails/5678-Piedmont-Rd-Atlanta-GA-30324/24681357_zpid/',
            'source': 'zillow',
            'created_at': '2025-01-13T09:15:00Z',
            'lat': 33.8148,
            'lng': -84.3674,
            'city': 'Atlanta',
            'state': 'GA',
            'county': 'Fulton',
            'zip_code': '30324',
            'property_category': 'residential',
            'property_type': 'apartment',
            'bedrooms': 1,
            'bathrooms': 1,
            'square_feet': 850,
            'lot_size': None,
            'year_built': 1980,
            'parking_spaces': 0,
            'has_garage': False,
            'has_pool': False,
            'has_gym': True,
            'pet_friendly': True,
            'crime_rate': 'medium',
            'flood_zone': 'X',
            'school_rating': 7.1,
            'sewage_system': 'municipal',
            'images': [
                'https://photos.zillowstatic.com/fp/5556667770-5678-Piedmont-Rd-Atlanta-GA-30324.jpg',
                'https://photos.zillowstatic.com/fp/5556667771-5678-Piedmont-Rd-Atlanta-GA-30324.jpg'
            ],
            'zillow_id': '24681357',
            'match_score': 0.76,
            'distance_meters': 1500,
            'price_diff_percent': -8.2,
            'agent_name': 'Lisa Chen',
            'agent_phone': '(678) 555-0789',
            'agent_email': 'lisa.chen@premierrealty.com',
            'brokerage': 'Premier Realty Group',
            'on_market': True
        },
        {
            'id': 4,
            'title': '9012 Roswell Rd, Sandy Springs, GA 30350',
            'price': 650000,
            'url': 'https://www.zillow.com/homedetails/9012-Roswell-Rd-Sandy-Springs-GA-30350/13579246_zpid/',
            'source': 'zillow',
            'created_at': '2025-01-12T14:20:00Z',
            'lat': 33.9845,
            'lng': -84.3514,
            'city': 'Sandy Springs',
            'state': 'GA',
            'county': 'Fulton',
            'zip_code': '30350',
            'property_category': 'residential',
            'property_type': 'townhouse',
            'bedrooms': 3,
            'bathrooms': 2.5,
            'square_feet': 2100,
            'lot_size': 0.1,  # acres
            'year_built': 2000,
            'parking_spaces': 2,
            'has_garage': True,
            'has_pool': False,
            'has_gym': False,
            'pet_friendly': True,
            'crime_rate': 'low',
            'flood_zone': 'X',
            'school_rating': 8.7,
            'sewage_system': 'municipal',
            'images': [
                'https://photos.zillowstatic.com/fp/2468135790-9012-Roswell-Rd-Sandy-Springs-GA-30350.jpg',
                'https://photos.zillowstatic.com/fp/2468135791-9012-Roswell-Rd-Sandy-Springs-GA-30350.jpg',
                'https://photos.zillowstatic.com/fp/2468135792-9012-Roswell-Rd-Sandy-Springs-GA-30350.jpg'
            ],
            'zillow_id': '13579246',
            'match_score': 0.87,
            'distance_meters': 2200,
            'price_diff_percent': -4.1,
            'agent_name': 'David Rodriguez',
            'agent_phone': '(770) 555-0321',
            'agent_email': 'david.rodriguez@homerealty.com',
            'brokerage': 'Home Realty Advisors',
            'on_market': True
        },

        # Commercial Properties
        {
            'id': 5,
            'title': '4567 Ponce De Leon Ave, Atlanta, GA 30307',
            'price': 2500000,
            'url': 'https://www.zillow.com/homedetails/4567-Ponce-De-Leon-Ave-Atlanta-GA-30307/97531824_zpid/',
            'source': 'commercial',
            'created_at': '2025-01-11T11:45:00Z',
            'lat': 33.7749,
            'lng': -84.2963,
            'city': 'Atlanta',
            'state': 'GA',
            'county': 'DeKalb',
            'zip_code': '30307',
            'property_category': 'commercial',
            'property_type': 'nnn_lease',
            'bedrooms': None,
            'bathrooms': None,
            'square_feet': 5000,
            'lot_size': 0.75,  # acres
            'year_built': 2010,
            'parking_spaces': 20,
            'has_garage': False,
            'has_pool': False,
            'has_gym': False,
            'pet_friendly': False,
            'crime_rate': 'low',
            'flood_zone': 'X',
            'school_rating': None,
            'sewage_system': 'municipal',
            'images': [
                'https://photos.zillowstatic.com/fp/8642135790-4567-Ponce-De-Leon-Ave-Atlanta-GA-30307.jpg',
                'https://photos.zillowstatic.com/fp/8642135791-4567-Ponce-De-Leon-Ave-Atlanta-GA-30307.jpg',
                'https://photos.zillowstatic.com/fp/8642135792-4567-Ponce-De-Leon-Ave-Atlanta-GA-30307.jpg'
            ],
            'zillow_id': '97531824',
            'match_score': 0.91,
            'distance_meters': 500,
            'price_diff_percent': 2.8,
            'agent_name': 'Robert Commercial',
            'agent_phone': '(404) 555-0198',
            'agent_email': 'robert@commercialatlanta.com',
            'brokerage': 'Commercial Atlanta Realty',
            'on_market': True
        },
        {
            'id': 6,
            'title': '7890 Peachtree Dunwoody Rd, Atlanta, GA 30328',
            'price': 8500000,
            'url': 'https://www.zillow.com/homedetails/7890-Peachtree-Dunwoody-Rd-Atlanta-GA-30328/64208571_zpid/',
            'source': 'commercial',
            'created_at': '2025-01-10T16:20:00Z',
            'lat': 33.9194,
            'lng': -84.3514,
            'city': 'Atlanta',
            'state': 'GA',
            'county': 'Fulton',
            'zip_code': '30328',
            'property_category': 'commercial',
            'property_type': 'office_building',
            'bedrooms': None,
            'bathrooms': None,
            'square_feet': 25000,
            'lot_size': 2.5,  # acres
            'year_built': 1988,
            'parking_spaces': 80,
            'has_garage': True,
            'has_pool': False,
            'has_gym': False,
            'pet_friendly': False,
            'crime_rate': 'low',
            'flood_zone': 'X',
            'school_rating': None,
            'sewage_system': 'municipal',
            'images': [
                'https://photos.zillowstatic.com/fp/3579246801-7890-Peachtree-Dunwoody-Rd-Atlanta-GA-30328.jpg',
                'https://photos.zillowstatic.com/fp/3579246802-7890-Peachtree-Dunwoody-Rd-Atlanta-GA-30328.jpg',
                'https://photos.zillowstatic.com/fp/3579246803-7890-Peachtree-Dunwoody-Rd-Atlanta-GA-30328.jpg',
                'https://photos.zillowstatic.com/fp/3579246804-7890-Peachtree-Dunwoody-Rd-Atlanta-GA-30328.jpg'
            ],
            'zillow_id': '64208571',
            'match_score': 0.88,
            'distance_meters': 1200,
            'price_diff_percent': -1.8,
            'agent_name': 'Jennifer Office',
            'agent_phone': '(770) 555-0654',
            'agent_email': 'jennifer@officerealtyatl.com',
            'brokerage': 'Office Realty Atlanta',
            'on_market': True
        },

        # Land and Agricultural
        {
            'id': 7,
            'title': '12345 Highway 78, Loganville, GA 30052',
            'price': 450000,
            'url': 'https://www.zillow.com/homedetails/12345-Highway-78-Loganville-GA-30052/86420975_zpid/',
            'source': 'land',
            'created_at': '2025-01-09T13:10:00Z',
            'lat': 33.8360,
            'lng': -83.9001,
            'city': 'Loganville',
            'state': 'GA',
            'county': 'Walton',
            'zip_code': '30052',
            'property_category': 'land',
            'property_type': 'farm',
            'bedrooms': None,
            'bathrooms': None,
            'square_feet': None,
            'lot_size': 20.0,  # acres
            'year_built': None,
            'parking_spaces': 0,
            'has_garage': False,
            'has_pool': False,
            'has_gym': False,
            'pet_friendly': True,
            'crime_rate': 'low',
            'flood_zone': 'X',
            'school_rating': 6.5,
            'sewage_system': 'septic',
            'images': [
                'https://photos.zillowstatic.com/fp/1597534680-12345-Highway-78-Loganville-GA-30052.jpg',
                'https://photos.zillowstatic.com/fp/1597534681-12345-Highway-78-Loganville-GA-30052.jpg',
                'https://photos.zillowstatic.com/fp/1597534682-12345-Highway-78-Loganville-GA-30052.jpg'
            ],
            'zillow_id': '86420975',
            'match_score': 0.79,
            'distance_meters': 150000,
            'price_diff_percent': -9.8,
            'agent_name': 'Tom Agricultural',
            'agent_phone': '(678) 555-0432',
            'agent_email': 'tom@agriculturalga.com',
            'brokerage': 'Agricultural Georgia Realty',
            'on_market': True
        },
        {
            'id': 8,
            'title': '6789 Ball Ground Hwy, Ball Ground, GA 30107',
            'price': 1200000,
            'url': 'https://www.zillow.com/homedetails/6789-Ball-Ground-Hwy-Ball-Ground-GA-30107/53186420_zpid/',
            'source': 'land',
            'created_at': '2025-01-08T09:30:00Z',
            'lat': 34.3381,
            'lng': -84.3769,
            'city': 'Ball Ground',
            'state': 'GA',
            'county': 'Cherokee',
            'zip_code': '30107',
            'property_category': 'land',
            'property_type': 'ranch',
            'bedrooms': None,
            'bathrooms': None,
            'square_feet': None,
            'lot_size': 50.0,  # acres
            'year_built': None,
            'parking_spaces': 0,
            'has_garage': False,
            'has_pool': False,
            'has_gym': False,
            'pet_friendly': True,
            'crime_rate': 'low',
            'flood_zone': 'X',
            'school_rating': 8.1,
            'sewage_system': 'well_septic',
            'images': [
                'https://photos.zillowstatic.com/fp/4682013579-6789-Ball-Ground-Hwy-Ball-Ground-GA-30107.jpg',
                'https://photos.zillowstatic.com/fp/4682013580-6789-Ball-Ground-Hwy-Ball-Ground-GA-30107.jpg',
                'https://photos.zillowstatic.com/fp/4682013581-6789-Ball-Ground-Hwy-Ball-Ground-GA-30107.jpg',
                'https://photos.zillowstatic.com/fp/4682013582-6789-Ball-Ground-Hwy-Ball-Ground-GA-30107.jpg'
            ],
            'zillow_id': '53186420',
            'match_score': 0.85,
            'distance_meters': 80000,
            'price_diff_percent': 6.3,
            'agent_name': 'Susan Ranch',
            'agent_phone': '(770) 555-0876',
            'agent_email': 'susan@ranchgeorgia.com',
            'brokerage': 'Ranch Georgia Realty',
            'on_market': True
        },
        {
            'id': 9,
            'title': '3456 Old Alabama Rd, Alpharetta, GA 30004',
            'price': 150000,
            'url': 'https://www.zillow.com/homedetails/3456-Old-Alabama-Rd-Alpharetta-GA-30004/75319864_zpid/',
            'source': 'land',
            'created_at': '2025-01-07T14:45:00Z',
            'lat': 34.0754,
            'lng': -84.2941,
            'city': 'Alpharetta',
            'state': 'GA',
            'county': 'Fulton',
            'zip_code': '30004',
            'property_category': 'land',
            'property_type': 'empty_land',
            'bedrooms': None,
            'bathrooms': None,
            'square_feet': None,
            'lot_size': 5.0,  # acres
            'year_built': None,
            'parking_spaces': 0,
            'has_garage': False,
            'has_pool': False,
            'has_gym': False,
            'pet_friendly': True,
            'crime_rate': 'low',
            'flood_zone': 'X',
            'school_rating': 8.9,
            'sewage_system': 'municipal',
            'images': [
                'https://photos.zillowstatic.com/fp/2468013579-3456-Old-Alabama-Rd-Alpharetta-GA-30004.jpg',
                'https://photos.zillowstatic.com/fp/2468013580-3456-Old-Alabama-Rd-Alpharetta-GA-30004.jpg'
            ],
            'zillow_id': '75319864',
            'match_score': 0.72,
            'distance_meters': 25000,
            'price_diff_percent': -12.1,
            'agent_name': 'David Land',
            'agent_phone': '(404) 555-0543',
            'agent_email': 'david@landgeorgia.com',
            'brokerage': 'Land Georgia Realty',
            'on_market': True
        }
    ]

def get_mock_stats():
    """Return mock statistics."""
    return {
        'total_deals': 156,
        'recent_deals': 23,
        'matched_deals': 89,
        'avg_match_score': 0.78
    }